### ISSUE TITLE
Package-Installation in «01_packages.R»

### ISSUE THREAD

**Issue by CGRBZH** [awelZH/airquality#1]
**tl;dr**: `require()` bricht eine der Grundregeln robuster Softwaresysteme: [fail early](https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so/2807375#2807375).

`require()` ist nett, installiert aber keine fehlenden Packages. `require()` gibt eine Warnung mit TRUE/FALSE aus und das Skript läuft weiter. Die Verwendung von `library()` anstelle von `require()` führt hier zu einer Fehlermeldung, die deutlich signalisiert, dass etwas nicht stimmt. 

--> Insbesondere relevant für rOstluft und rOstluft.plot, da diese von GitHub geladen werden müssen.

Falls das Skript beibehalten wird, empfehlen wir, es etwas umzuschreiben:

```
if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
}
```

Für mehrere Packages könnte das dann so aussehen:

```
for (package in c('<package1>', '<package2>')) {
    if (!require(package, character.only=T, quietly=T)) {
        install.packages(package)
        library(package, character.only=T)
    }
}
```

**Comment by Sintermann** [comment]
DESCRIPTION angepasst / weiter mit load_all() / wird mit FIXME bereinigt
