### ISSUE TITLE
cols über Index abfragen

### ISSUE THREAD

**Issue by CGRBZH** [awelZH/airquality#2]
Spalten werden über ihren Index aufgerufen. Dies hat Nachteile:

1. Die Reihenfolge der Spalten kann sich ändern und der Code funktioniert trotzdem, da die Indizes noch existieren. Wenn das Skript dann erst 500 Zeilen später failed, wird das Debugging schnell mal mühsam. Und im schlechtesten Fall liefert das Skript falsche Ergebnisse.
2. Es widerspricht dem Prinzip des Fail early ;) 

Aufgefallen bspw. in «02_functions.R» in Zeilen:
15: `data <- readr::read_delim(file, col_select = c(-(1:10)), delim =";", locale = locale)`
157: `header <- header[c(1, 4, 8, 7), ]`

**Empfehlung:** 
Spalten immer mit ihrem Namen aufrufen. Wenn sie nicht mehr existieren oder ihre Namen geändert wurden, wird das Skript direkt an diesem Schritt scheitern.

**Comment by Sintermann** [comment]
siehe #7
