### ISSUE TITLE
Arias als Datenquelle langfristig gesichert?

### ISSUE THREAD

**Issue by CGRBZH** [awelZH/airquality#3]
Ihr ladet gewisse Daten des Bundesamtes für Umwelt BAFU/NABEL von [arias.ch](https://www.arias.ch/).

Die Firma Arias befindet sich in Liquidation. 

Hat das einen Einfluss auf die Verfügbarkeit der Daten aus dieser Quelle?

**Comment by Sintermann** [comment]
funktion / Datenquelle wird bei Bedarf angepasst
