### ISSUE TITLE
Kein Zugriff auf https://ckan.opendata.swiss/api/

### ISSUE THREAD

**Issue by CGRBZH** [awelZH/airquality#4]
Sowohl von der lokalen R-Installation als auch vom R-Server:

`httr2::request("https://ckan.opendata.swiss/api/3/action/package_show?id=luftschadstoffemissionen-im-kanton-zurich")` 
Gibt ein **403 from proxy** zurück.

@ThomasKnecht prüft, wo das Problem liegt.

Gegebenenfalls müssen im README oder der Dokumentation Hinweise zu Proxy-Einstellungen gegeben werden.

**Comment by ThomasKnecht** [comment]
ist bei uns auf dem server ein proxy problem... müssen da die seite freischalten lassen. vermute ich

**Comment by Sintermann** [comment]
Server Stat-Amt
