### ISSUE TITLE
Allgemeines Feedback und Anregungen

### ISSUE THREAD

**Issue by CGRBZH** [awelZH/airquality#5]
**Feedback:**

1. Laden von Packes besser implementieren: Entweder wie in Issue #1 beschrieben oder das Projekt in Package-Struktur bringen. Ziel sollte es auch immer sein, so wenig wie möglich Packages laden zu müssen.
2. Spalten über ihren Namen anstatt den Index aufrufen (siehe Issue #2 )
3. Für die STATPOP-Daten sind die Jahre aktuell hardcoded, das kann geskriptet werden.
4. Nicht optimal, dass Funktionen derzeit den Datenimport das Data wrangling in einem machen. Die Strukturierung der Funktionen kann optimiert werden. Siehe Punkt 2 unter Anregungen. Das hängt aber auch von den Anforderungen ab.
5. Funktionen, Funktionen, Funktionen --> @ThomasKnecht macht einen Vorschlag für ein zwei Funktionen ohne die Struktur grundlegend zu überarbeiten, bspw.: `replace_no2_ps`, `replace_pm10` und `replace_pm25` in eine` replace()`-Funktion umschreiben oder  `read_arias()` umschreiben ohne dass x-mal `read()` / `pull()` gemacht wird 

**Anregungen:**

1. Das Projekt in die [Package-Struktur](https://scv.bu.edu/examples/r/tutorials/BuildingPackages/r-project-setup.html#r-package-structure) bringen. Bietet viele Vorteile, u.a. werden Funktionen besser beschrieben, es gibt eine gute Übersicht über Packages und Dependencies und es lassen sich Schritte besser automatisieren.
2. Funktionen thematisch aufteilen, bspw. in `read_`, `prepare_`, `plot_` und `write_`-Funktionen, und diese mit klaren Funktionsbeschreibungen versehen.
3. Ambitionen nochmals schärfen: Wer sind die Nutzer:innen? Wie automatisierbar muss oder kann es sein? Wie Fail Safe sollte es sein?
4. Fail early besser abstützen indem Tests eingebaut werden. Bspw. nach Datenimports mit dem [validate-Package](https://cran.r-project.org/web/packages/validate/vignettes/cookbook.html) oder beim Datendownload mit [`tryCatch()`](https://www.r-bloggers.com/2020/10/basic-error-handing-in-r-with-trycatch/) ein Fehlerhandling definieren
5. Monitoring von automatischen Prozessen, bspw. mit GH Actions
6. Den Bericht als [pkgdown](https://github.com/r-lib/pkgdown)-Seite oder mit [Quarto ](https://quarto.org/) veröffentlichen?
7. Damit die grafischen Darstellungen besser im kantonalen Corpoarte Design daher kommen, hat das STAT in [statR](https://statistikzh.github.io/statR/articles/Visualisierungen.html#farbpaletten-barrierefreiheit)-Package Farbpaletten im kantonalen CI/CD hinterlegt. Dürft auch ihr sehr gerne nutzen (obwohl das Wes Anderson Package schon echt cool ist 😄 )

**Comment by Sintermann** [comment]
teils adressiert, zur Übersicht noch offen lassen

**Comment by Sintermann** [comment]
teils erledigt, Rest in einzelnen Issues
